import { MongoClient } from "mongodb";
import { writeFileSync } from "node:fs";
import {
  transformUser, transformResource, transformTransaction, transformAnnouncement,
  transformDeletedAccountLog, transformNotification, transformBookmark, transformDownloadLog,
} from "./transform.js";
import { buildInsertStatements } from "./sqlWriter.js";

const MONGODB_URI = process.env.MONGODB_URI;
const OUTPUT_FILE = process.env.OUTPUT_FILE || "migration-data.sql";

if (!MONGODB_URI) {
  console.error("Set MONGODB_URI to your production connection string before running this.");
  console.error("Example: MONGODB_URI='mongodb+srv://...' node export.js");
  process.exit(1);
}

// Mongoose's default collection naming: lowercase the model name and
// pluralize with no separator — "DownloadLog" becomes "downloadlogs", NOT
// "download_logs". These must match exactly what's actually in Atlas.
const COLLECTIONS = {
  users: { table: "users", transform: transformUser },
  resources: { table: "resources", transform: transformResource },
  transactions: { table: "transactions", transform: transformTransaction },
  announcements: { table: "announcements", transform: transformAnnouncement },
  deletedaccountlogs: { table: "deleted_account_logs", transform: transformDeletedAccountLog },
  notifications: { table: "notifications", transform: transformNotification },
  bookmarks: { table: "bookmarks", transform: transformBookmark },
  downloadlogs: { table: "download_logs", transform: transformDownloadLog },
};

async function run() {
  const client = new MongoClient(MONGODB_URI, { readPreference: "secondaryPreferred" });
  await client.connect();
  const db = client.db();

  const sqlParts = [
    "-- Generated by scripts/migrate/export.js — review before running.",
    `-- Source: MongoDB, exported ${new Date().toISOString()}`,
    "",
    "-- Bulk-load pattern: FK enforcement is off for the import itself (so",
    "-- table insert order doesn't matter), then explicitly turned back on",
    "-- and verified against orphaned references afterward — see",
    "-- verify.js, run separately after this file is applied.",
    "PRAGMA foreign_keys = OFF;",
    "BEGIN TRANSACTION;",
    "",
  ];

  const counts = {};

  for (const [collectionName, { table, transform }] of Object.entries(COLLECTIONS)) {
    const docs = await db.collection(collectionName).find({}).toArray();
    const rows = docs.map(transform);
    counts[collectionName] = rows.length;

    sqlParts.push(`-- ${collectionName} (${rows.length} rows)`);
    if (rows.length > 0) {
      sqlParts.push(...buildInsertStatements(table, rows));
    }
    sqlParts.push("");
  }

  sqlParts.push("COMMIT;");
  sqlParts.push("PRAGMA foreign_keys = ON;");

  writeFileSync(OUTPUT_FILE, sqlParts.join("\n"));

  console.log("Exported:");
  for (const [name, count] of Object.entries(counts)) {
    console.log(`  ${name}: ${count}`);
  }
  console.log(`\nWrote ${OUTPUT_FILE}`);
  console.log("\nNext steps:");
  console.log("  1. Review the file — it's plain SQL, readable top to bottom.");
  console.log(`  2. Apply it: npx wrangler d1 execute sharef-db --remote --file=${OUTPUT_FILE}`);
  console.log("  3. Verify it: npx wrangler d1 execute sharef-db --remote --file=scripts/migrate/verify.sql");
  console.log("     Every count in that output should be 0.");

  await client.close();
}

run().catch((err) => {
  console.error("Export failed:", err.message);
  process.exit(1);
});
